apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "durak-online.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.rollout.strategy }}
    {{- if eq .Values.rollout.strategy "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.rollout.maxSurge }}
      maxUnavailable: {{ .Values.rollout.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ include "durak-online.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "durak-online.fullname" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "durak-online.fullname" . }}-config
            - secretRef:
                name: {{ include "durak-online.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
