apiVersion: v1
kind: Secret
metadata:
  name: {{ include "durak-online.fullname" . }}-secret
type: Opaque
stringData:
  POSTGRES_URL: {{ .Values.secrets.postgresUrl | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
